//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyPurchas
    {
        public long CustomerId { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public System.TimeSpan PurchaseTime { get; set; }
        public string BillDescription { get; set; }
        public Nullable<long> UserPayment { get; set; }
        public long BillAmount { get; set; }
    }
}
